#ifndef __SRV_PLUGIN__MSGSTATS_H__
# define __SRV_PLUGIN__MSGSTATS_H__

#define MSG_NAME "REQ_STATS"

#define MSGKEY_PATTERN "PATTERN"

#define MSGFIELD_STATPREFIX "stat:"

#define MSGFIELD_STATKEY_MAXLEN 256
#define MSGFIELD_STATVAL_MAXLEN 64

#endif /*__SRV_PLUGIN__MSGSTATS_H__*/
