sudo: required
dist: xenial
language: c
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse'
    - sourceline: 'deb http://mirror.openio.io/pub/repo/openio/sds/18.04/ubuntu/ xenial/'
      key_url: 'http://mirror.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0'
install:
  - sudo bash -c "echo '/tmp/core.%p.%E' > /proc/sys/kernel/core_pattern"
  - mkdir /tmp/oio
  - sudo apt update -qq
  - sudo apt install -y --force-yes -qq $(awk '{print $1}' ci/deps-ubuntu-bionic.txt)
  - ./ci/user-deps.sh
  - git fetch --tags
  - git submodule update --init --recursive

env:
  global:
  - CMAKE_OPTS="-DENABLE_CODECOVERAGE=on -DCMAKE_INSTALL_PREFIX=/tmp/oio -DLD_LIBDIR=lib -DZK_LIBDIR=/usr/lib -DZK_INCDIR=/usr/include/zookeeper -DAPACHE2_LIBDIR=/usr/lib/apache2 -DAPACHE2_INCDIR=/usr/include/apache2 -DAPACHE2_MODDIR=/tmp/oio/lib/apache2/module"
  - G_DEBUG=fatal_warnings
  - G_DEBUG_LEVEL=W
  - ZK=127.0.0.1:2181
  - LD_LIBRARY_PATH=/tmp/oio/lib
  - PKG_CONFIG_PATH=/tmp/oio/lib/pkgconfig

jobs:
  fast_finish: true
  include:
    - stage: Fail Fast tests
      script: ./tools/oio-travis-failfast.sh
      name: Copyright, Release build, SDK build
    - script: ./tools/oio-travis-unit.sh
      name: C unit/func, Python unit/pep8
    - stage: Functional tests (fast)
      script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=slave
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=cli
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=worm
    - stage: Functional tests
      script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=single
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=repli,go-rawx
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=ec
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=3copies
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=small-cache,fsync
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=3copies,with-service-id
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=ec,with-random-service-id
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=rebuilder,with-service-id
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=multi-beanstalk
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=mover,with-service-id
    - script: ./tools/oio-travis-suites.sh
      env: TEST_SUITE=webhook

after_success:
  - bash <(curl -s https://codecov.io/bash) -f /tmp/cmake_coverage.output
  - codecov
  - if cat ${HOME}/go_coverage.output.* > go_coverage.output; then rm ${HOME}/go_coverage.output.*; else echo "" > go_coverage.output; fi
  - bash <(curl -s https://codecov.io/bash) -f go_coverage.output
