ovh.companion.analyze=auto
ovh.companion.cds.project=OPENIO
ovh.companion.cds.workflow=oio-sds
ovh.companion.archive.artifact.download=oio-sds.build_sonar.tar.gz
ovh.companion.install=echo 'deb [trusted=yes] http://last-public-ovh-pcs.snap.mirrors.ovh.net/ubuntu focal main' >> /etc/apt/sources.list.d/obsto.list && apt-get update && apt-get install -y $(tr '\n' ' ' < $(pwd)/.cds/deps-ubuntu-focal.txt)
ovh.companion.before_analyze=sed -i s#/tmp/[0-9a-f]*/run#$(pwd)#g $(pwd)/build/debug/build-wrapper-dump.json && sonar-scanner -X
sonar.sources=.
sonar.exclusions=debian/**,vendor/**,docs/**,.build/**,.cds/**,.github/**,tools/**,python-patches/**,Testing/**,tests/**
sonar.tests=tests
sonar.go.coverage.reportPaths=go_coverage/*.json
sonar.cfamily.gcov.reportsPath=cmake_coverage.*
sonar.python.coverage.reportPaths=.coverage.*
sonar.cfamily.build-wrapper-output=build/debug