version: v1.0
name: oio-sds-build
jobs:
  - job: Package for ubuntu/20.04
    steps:

      - gitClone:
          branch: '{{ .git.branch }}'
          commit: '{{ .git.hash }}'
          depth: "false"
          directory: '{{ .cds.workspace }}'
          privateKey: proj-ssh-openio
          url: '{{ .git.url }}'

      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Build package and upload
        script: |+
          #!/bin/bash
          exec &> >(tee -a package-20.04.log)
          trap 'worker upload package-20.04.log' EXIT
          cat $0
          set -x
          set -e
          . .cds/versions
          if [[ "{{ .git.branch }}" =~ ^dev/[a-z0-9]+/feature_ || "{{ .git.branch }}" =~ ^feature/ ]]; then
            export VERSION=1.${CDS_VERSION}-focal
            PACKAGE="{{ .git.branch }}"
            PACKAGE="${PACKAGE#dev/*/}" # remove dev/login*/ prefix
            PACKAGE="${PACKAGE//[^a-zA-Z0-9]/-}" # sanitize package name
            export PACKAGE="oio-sds-${PACKAGE}"
          else
            # dev or prod release
            export VERSION=1.0-focal
            PACKAGE=oio-sds
            if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
              PACKAGE=${PACKAGE}-{{ .git.tag }}
            else
              PACKAGE=${PACKAGE}-$(date +%Y%m%d%H%M).git{{ .git.hash.short }}
            fi
            if [[ "{{ .git.branch }}" == "master" || "{{ .git.tag }}" =~ ^[0-9]+\. ]]; then
              export OBSTO_BUILD="ovh${CDS_VERSION}"
            else
              export OBSTO_BUILD="ovhdev${CDS_VERSION}"
            fi
            export PACKAGE=${PACKAGE}-${OBSTO_BUILD}
          fi
          export REPO_SUBREPO=main
          export REPO_LIMIT=0
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"

          export PACKAGE_RAWX=${PACKAGE/#oio-sds-/oio-sds-rawx-}
          export PACKAGE_OIOPROXY=${PACKAGE/#oio-sds-/oio-sds-oioproxy-}
          export PACKAGE_META0=${PACKAGE/#oio-sds-/oio-sds-meta0-}
          export PACKAGE_META1=${PACKAGE/#oio-sds-/oio-sds-meta1-}
          export PACKAGE_META2=${PACKAGE/#oio-sds-/oio-sds-meta2-}
          export PACKAGE_RDIR=${PACKAGE/#oio-sds-/oio-sds-rdir-}
          export PACKAGE_CONSCIENCE=${PACKAGE/#oio-sds-/oio-sds-conscience-}

          make -f /external-packages/ubuntu/focal/Makefile.common install-apt-repo
          make -f /external-packages/ubuntu/focal/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/focal/Makefile.common
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_artifacts
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-20.04

  - job: Publish Python package on Artifactory
    steps:
      - name: Checkout application
        checkout: "{{ .cds.workspace }}"

      - name: Install dependencies
        script: |+
          #!/bin/bash
          eval $(worker key install --env-git proj-ssh-openio)
          . .cds/versions
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y python3-virtualenv virtualenv
          virtualenv -p /usr/bin/python3 $HOME/oiovenv
          cat << EOF > $HOME/oiovenv/pip.conf
          [global]
          index-url = https://${PYPI_SNAPSHOT}-pypi.snap.mirrors.ovh.net/simple/
          [install]
          progress-bar = off
          EOF
          . $HOME/oiovenv/bin/activate
          pip install --progress-bar off --upgrade pip build twine
          pip install --progress-bar off -e ".[all]"
          # Need to fetch tags and enough commits for pbr to build a correct version number
          git fetch origin master --depth 500 --tags

      - name: Build Python package
        script: |+
          #!/bin/bash
          . $HOME/oiovenv/bin/activate
          python -m build --no-isolation

      - name: Publish Python package
        script: |+
          #!/bin/bash
          . $HOME/oiovenv/bin/activate
          if [ "{{ .git.branch }}" == "master" ]
          then
            MATURITY="release"
          else
            MATURITY="snapshot"
          fi
          export TWINE_USERNAME="${CDS_INTEGRATION_ARTIFACT_MANAGER_TOKEN_NAME}"
          export TWINE_PASSWORD="${CDS_INTEGRATION_ARTIFACT_MANAGER_TOKEN}"
          export TWINE_REPOSITORY_URL="https://artifactory.ovhcloud.tools/artifactory/api/pypi/pu-objectstorage-default-pypi-${MATURITY}"
          twine upload --non-interactive dist/*

    requirements:
      - model: Python-official-3.12-bookworm
