version: v1.0
name: oio-sds-test-fast
jobs:
  - job: Run fast tests
    steps:

      - gitClone:
          branch: '{{ .git.branch }}'
          commit: '{{ .git.hash }}'
          depth: "false"
          directory: '{{ .cds.workspace }}'
          privateKey: proj-ssh-openio
          url: '{{ .git.url }}'

      - name: Install dependencies
        script: |+
          #!/bin/bash
          apt install -y gnupg software-properties-common
          set -x
          curl http://mirror2.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0 | apt-key add -
          apt-add-repository "deb http://mirror2.openio.io/pub/repo/openio/sds/20.04/ubuntu/ bionic/"
          apt-add-repository ppa:longsleep/golang-backports
          apt install -y $(tr '\n' ' ' < .cds/deps-ubuntu-bionic.txt)
          mkdir /tmp/oio
          virtualenv -p /usr/bin/python3 $HOME/oioenv
          . $HOME/oioenv/bin/activate
          pip install --upgrade pip setuptools virtualenv tox -r all-requirements.txt -r test-requirements.txt

      - name: Run fast tests
        script:
          - pgrep rsyslogd || rsyslogd &
          - . $HOME/oioenv/bin/activate
          - ./tools/oio-travis-failfast.sh

      - name: Run unit tests
        script:
          - . $HOME/oioenv/bin/activate
          - ./tools/oio-travis-unit.sh

    requirements:
      - model: Ubuntu-18.04-VM-b2-07
        #- model: ubuntu-bionic
        #- model: openio-debbuild-18.04
