version: v1.0
name: oio-sds-lint
jobs:
  - job: Run coding style tests
    steps:
      - name: Checkout application
        checkout: "{{ .cds.workspace }}"

      - name: Install dependencies
        script:
          - set -x
          - export DEBIAN_FRONTEND=noninteractive
          - eval $(worker key install --env-git proj-ssh-openio)
          - apt update
          # We don't need docker compose
          - apt install -y $(sed -e '/docker-compose-plugin/d' .cds/deps-ubuntu-focal.txt | tr '\n' ' ')
          - virtualenv -p /usr/bin/python3 $HOME/venv
          - . $HOME/venv/bin/activate
          - pip install -i "https://${CDS_INTEGRATION_ARTIFACT_MANAGER_TOKEN_NAME}:${CDS_INTEGRATION_ARTIFACT_MANAGER_TOKEN}@artifactory.ovhcloud.tools/artifactory/api/pypi/pypi-remote/simple" --progress-bar off -r requirements.txt -r test-requirements.txt


      - name: Run coding style tests
        script:
          - set -x
          - . $HOME/venv/bin/activate
          - ruff format --diff "oio" "tests" "tools" "bin" --exclude="oio-bootstrap.py"
          - ruff check "oio" "tests" "tools" "bin" --exclude="oio-bootstrap.py"

    requirements:
      - model: ubuntu-focal
